### PR TITLE
Rename projects

### LINKED ISSUE #57: Add ChakraCore to lib/exe names
In order to make it clearer that the files are related to ChakraCore, let's add ChakraCore to the name.

Consider renaming from:

Debug.Protocol.lib
Debug.ProtocolHandler.lib
Debug.Sample.exe

to:

ChakraCore.DebugProtocol.lib
ChakraCore.DebugProtocolHandler.lib
ChakraCore.DebugSample.exe

### PR DESCRIPTION
**Pull request by kfarnung**
Projects are now named "ChakraCore.Debugger.*" and all build ouptuts
drop in the "/build/" directory of the repo.

Fixes #57

### CODE REVIEW

**Comment by akrantz** [comment]
@kfarnung Please rename "Win32" project configs to "x86" to match solution config. Please add ARM project configs.

**Comment by kfarnung** [comment]
@akrantz I can add ARM, but I think Win32 is just the name of the platform, I don't think I have any control over that.

**Comment by kfarnung** [comment]
I'm going to land this PR now and we can iterate on naming later.

**Comment by jackhorton** [comment]
ChakraCore's 32bit target is "x86" while chakra's is "win32". I can help out with the vcxproj and sln setup if you'd like on monday.

**Pull request merged**
