### PR TITLE
Add support for source maps

### LINKED ISSUE #11: Parse SourceUrl and SourceMappingUrl out of the script source

### PR DESCRIPTION
**Pull request by kfarnung**
When a script is loaded, parse the file for `sourceMappingURL` and
`sourceURL` values.

Fixes #11

### CODE REVIEW

**Comment by akrantz** [comment]
@kfarnung Do you have any samples / test cases for this?

**Comment by kfarnung** [comment]
No test cases, but this is a standard feature:  https://www.html5rocks.com/en/tutorials/developertools/sourcemaps/

I tested it out locally using a TypeScript project that has source maps enabled.

**Comment by akrantz** [comment]
Yes, but there are more possibilities there. A simple case is a file with the source map comment at the end. But multiple files can be bundled into a single file (bundle.js) which has multiple source map lines embedded.

Also, it would be good to look at the source map spec to understand the possible syntax. File names only, relative paths, full paths, urls, path separator chars etc.

**Comment by kfarnung** [comment]
There can only be one `sourceMappingURL` and/or `sourceURL` comment per file, that's all that the protocol allows me to return.  The map is a one-to-many relationship between the generated code and the source, so there's no need for more than one source map file.

The debugger API doesn't do anything to the path provided, it's just sent back to the debugger unprocessed.  It's up to the code generator and the debugger to agree, but the engine doesn't do anything with that data.  The paths are usually relative to the build drop, in my example the *.map file was dropped right next to the JS file:

```javascript
//# sourceMappingURL=index.js.map
```

And the map file includes the relative path to the source file:

```json
{"version":3,"file":"index.js","sourceRoot":"","sources":["../src/index.ts"],"names":[],"mappings":";AAOA,IAAI,OAAO,IAAI,KAAK,WAAW,EAAE;IAC/B,IAAI,GAAG;QACL,IAAI,EAAE,OAAO,CAAC,GAAG;QACjB,WAAW,EAAE,OAAO,CAAC,IAAI;KAC1B,CAAC;CACH;AAED,KAAkB,UAAc,EAAd,KAAA,IAAI,CAAC,SAAS,EAAd,cAAc,EAAd,IAAc;IAA3B,IAAM,GAAG,SAAA;IACV,IAAI,CAAC,IAAI,CAAC,gBAAc,GAAK,CAAC,CAAC;CAClC;AAED;IACE;QACE,IAAI,CAAC,GAAG,EAAE,CAAC;QACX,CAAC,IAAI,CAAC,CAAC;QACP,OAAO,CAAC,CAAC;IACX,CAAC;IAED,IAAI,CAAC,GAAG,EAAE,CAAC;IACX,CAAC,IAAI,SAAS,EAAE,CAAC;IACjB,CAAC,IAAI,IAAI,CAAC;IACV,OAAO,CAAC,CAAC;AACX,CAAC;AAED;IACE,IAAI;QACF,MAAM,EAAE,GAAG,EAAE,CAAC,EAAE,GAAG,EAAE,CAAE,CAAC,EAAE,CAAC,EAAE,CAAC,CAAE,EAAE,CAAC;KACpC;IAAC,OAAO,CAAC,EAAE;QACV,OAAO,KAAK,CAAC;KACd;AACH,CAAC;AAED,IAAI,MAAM,GAAG,OAAO,EAAE,CAAC;AACvB,IAAI,CAAC,IAAI,CAAC,UAAU,EAAE,CAAC,CAAC;AACxB,IAAI,CAAC,IAAI,CAAC,MAAM,CAAC,CAAC;AAElB,CAAC,CAAC"}
```

I also tested out inline source maps in TypeScript, that drops in a base64-encoded version of the map:

```javascript
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiaW5kZXguanMiLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyIuLi9zcmMvaW5kZXgudHMiXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IjtBQU9BLElBQUksT0FBTyxJQUFJLEtBQUssV0FBVyxFQUFFO0lBQy9CLElBQUksR0FBRztRQUNMLElBQUksRUFBRSxPQUFPLENBQUMsR0FBRztRQUNqQixXQUFXLEVBQUUsT0FBTyxDQUFDLElBQUk7S0FDMUIsQ0FBQztDQUNIO0FBRUQsS0FBa0IsVUFBYyxFQUFkLEtBQUEsSUFBSSxDQUFDLFNBQVMsRUFBZCxjQUFjLEVBQWQsSUFBYztJQUEzQixJQUFNLEdBQUcsU0FBQTtJQUNWLElBQUksQ0FBQyxJQUFJLENBQUMsZ0JBQWMsR0FBSyxDQUFDLENBQUM7Q0FDbEM7QUFFRDtJQUNFO1FBQ0UsSUFBSSxDQUFDLEdBQUcsRUFBRSxDQUFDO1FBQ1gsQ0FBQyxJQUFJLENBQUMsQ0FBQztRQUNQLE9BQU8sQ0FBQyxDQUFDO0lBQ1gsQ0FBQztJQUVELElBQUksQ0FBQyxHQUFHLEVBQUUsQ0FBQztJQUNYLENBQUMsSUFBSSxTQUFTLEVBQUUsQ0FBQztJQUNqQixDQUFDLElBQUksSUFBSSxDQUFDO0lBQ1YsT0FBTyxDQUFDLENBQUM7QUFDWCxDQUFDO0FBRUQ7SUFDRSxJQUFJO1FBQ0YsTUFBTSxFQUFFLEdBQUcsRUFBRSxDQUFDLEVBQUUsR0FBRyxFQUFFLENBQUUsQ0FBQyxFQUFFLENBQUMsRUFBRSxDQUFDLENBQUUsRUFBRSxDQUFDO0tBQ3BDO0lBQUMsT0FBTyxDQUFDLEVBQUU7UUFDVixPQUFPLEtBQUssQ0FBQztLQUNkO0FBQ0gsQ0FBQztBQUVELElBQUksTUFBTSxHQUFHLE9BQU8sRUFBRSxDQUFDO0FBQ3ZCLElBQUksQ0FBQyxJQUFJLENBQUMsVUFBVSxFQUFFLENBQUMsQ0FBQztBQUN4QixJQUFJLENBQUMsSUFBSSxDQUFDLE1BQU0sQ0FBQyxDQUFDO0FBRWxCLENBQUMsQ0FBQyJ9
```

**Comment by akrantz** [comment]
Your implementation will take the first instance of ```//# sourceMappingURL=``` or ```//# sourceURL=```. It also accepts ```//@```.  That seems fine.

One concern is that debugging works with TypeScript compiled to JavaScript and then bundled into a single file. As I read through the [webpack guide on sourcemaps](https://webpack.js.org/guides/typescript/#source-maps), it appears that this produces JavaScript with inline source maps which are processed so that the final bundle.js file also has an associated bundle.js.map file. The bundle.js file would then have a single //# sourceMappingURL=bundle.js.map.

This all seems good.

**Comment by kfarnung** [comment]
One correction, this actually takes the last instance if there are multiple in the file. The value keeps getting overwritten by the subsequent matches. This was a conscious decision given that the convention is to place them at the end, but if you have any pointers to situations where there are multiple in the same file and the last one isn't the right one, please let me know.

**Comment by akrantz** [comment]
That makes sense. I don't know whether or not it is possible to have multiple in the same file, which is why I wanted to clarify the behavior.

**Comment by sethbrenith** [comment]
You might take a look at [F12's implementation](https://microsoft.visualstudio.com/OS/_search?type=code&lp=code-Project&text=findSourceAttribute&filters=ProjectFilters%7BOS%7DRepositoryFilters%7Bos%7DBranchFilters%7Bofficial%2Frsmaster%7DPathFilters%7B%2Finetcore%7D&_a=contents&result=DefaultCollection%2FOS%2Fos%2FGBofficial%2Frsmaster%2F%2Finetcore%2Fdevtoolbar%2Fv4%2Ffrontend%2Fdebugger%2FDocuments%2FSourceMapUrlParser.ts) to see if there are any other cases worth covering. It looks like they support `/*...*/` style comments, and require the comment to be on a separate line (you could start the regex with `^\\s*` to enforce this).

**Comment by kfarnung** [comment]
@sethbrenith Does the spec require the comments to be on their own line?  I decided not to validate that since there's no technical reason why a comment can't be at the end of a real line (thinking about the minifier scenario).

I updated the PR to also handle `/* … */` but only in cases where they are both on the same line

**Pull request merged**
